# Makefile.in generated automatically by automake 1.4c from Makefile.am

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /home/wolfgang/gift-0.1.6pre/../GIFTInstall
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

pkgdatadir = $(datadir)/gift
pkglibdir = $(libdir)/gift
pkgincludedir = $(includedir)/gift

top_builddir = ../..

ACLOCAL = ${SHELL} /home/wolfgang/gift-0.1.6pre/missing --run aclocal
AUTOCONF = ${SHELL} /home/wolfgang/gift-0.1.6pre/missing --run autoconf
AUTOMAKE = ${SHELL} /home/wolfgang/gift-0.1.6pre/missing --run automake
AUTOHEADER = ${SHELL} /home/wolfgang/gift-0.1.6pre/missing --run autoheader

INSTALL = /usr/bin//ginstall -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :


host_alias = @host_alias@
host_triplet = i686-pc-linux-gnu
AMDEP = #
AMTAR = ${SHELL} /home/wolfgang/gift-0.1.6pre/missing --run tar
AS = @AS@
AWK = gawk
BAYESIAN = 
BAYESIAN_LD_ADD = 
CC = gcc
CONVERT = /usr/bin/X11/convert
CPP = /lib/cpp
CXX = g++
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DOXYGEN = /usr/bin//doxygen
ECHO = echo
EMACS = emacs
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GIFT_BAYESIAN_FLAG = 
GIFT_INTERNAL_FLAG = 
GIFT_INTERNAL_PERLS = 
GIFT_LIB_VERSION_INFO = -version-info 0:1:5
LEX = @LEX@
LIBADD_DL = @LIBADD_DL@
LIBOBJS = @LIBOBJS@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = ./ltmain.sh
LN_S = ln -s
MAINT = @MAINT@
MAKEINFO = ${SHELL} /home/wolfgang/gift-0.1.6pre/missing --run makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = gift
PERL = /usr/local/bin/perl
PERL_LD_ADD = -rdynamic  -L/usr/local/lib /usr/local/lib/perl5/5.6.0/i686-linux/auto/DynaLoader/DynaLoader.a -L/usr/local/lib/perl5/5.6.0/i686-linux/CORE -lperl -lnsl -lndbm -lgdbm -ldbm -ldb -ldl -lm -lc -lposix -lcrypt
PRE_INSTALL_LIBDIRS = -L/home/wolfgang/gift-0.1.6pre/libMRML/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcPerl/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuPerl/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcInvertedFile/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcHierarchy/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcDistanceMatrix/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuInvertedFile/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuBayesian/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuHierarchy/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcURL2FTS/cc/
PRE_INSTALL_LINKDIRS = --rpath/home/wolfgang/gift-0.1.6pre/libMRML/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcPerl/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuPerl/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTAcInvertedFile/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTAcHierarchy/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTAcDistanceMatrix/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTQuInvertedFile/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTQuBayesian/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTQuHierarchy/cc/ --rpath/home/wolfgang/gift-0.1.6pre/libGIFTAcURL2FTS/cc/
PYTHON = @PYTHON@
PYTHON_EXEC_PREFIX = @PYTHON_EXEC_PREFIX@
PYTHON_PLATFORM = @PYTHON_PLATFORM@
PYTHON_PREFIX = @PYTHON_PREFIX@
PYTHON_SITE = @PYTHON_SITE@
PYTHON_SITE_EXEC = @PYTHON_SITE_EXEC@
PYTHON_SITE_INSTALL = @PYTHON_SITE_INSTALL@
PYTHON_SITE_PACKAGE = @PYTHON_SITE_PACKAGE@
PYTHON_VERSION = @PYTHON_VERSION@
RANLIB = ranlib
SGML2INFO = 
SGML2LATEX = 
SGML2TXT = 
STRIP = strip
U = @U@
UNPUBLISHED = 
VERSION = 0.1.5pre
WEB_PUBLISHING_DIRECTORY = /user/u7/muellerw/public_html/
WEB_PUBLISHING_LOCATION = http://localhost/~muellerw
install_sh = ./install-sh
lispdir = ${datadir}/emacs/site-lisp
multi_basedir = @multi_basedir@
pythondir = @pythondir@

#     -*- mode: makefile -*-

#     GIFT, a flexible content based image retrieval system.
#     Copyright (C) 1998, 1999, 2000 CUI, University of Geneva

#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#
#Makefile for the inverted File library
#


lib_LTLIBRARIES = libGIFTAcDistanceMatrix.la

libGIFTAcDistanceMatrix_la_LDFLAGS = "-L/home/wolfgang/gift-0.1.6pre/libMRML/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcPerl/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuPerl/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcInvertedFile/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcHierarchy/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcDistanceMatrix/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuInvertedFile/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuBayesian/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTQuHierarchy/cc/ -L/home/wolfgang/gift-0.1.6pre/libGIFTAcURL2FTS/cc/" -lMRML -lGIFTAcInvertedFile -lGIFTAcURL2FTS

INCLUDES = -DHAS_BOOL -I$(top_srcdir)/libMRML/include -I$(top_srcdir)/libGIFTAcInvertedFile/include -I$(top_srcdir)/libGIFTAcDistanceMatrix/include -I$(top_srcdir)/libGIFTAcURL2FTS/include -I$(top_srcdir)/libGIFTQuBayesian/include

libGIFTAcDistanceMatrix_la_SOURCES = \
	 \
	plug_in_fo.cc

subdir = libGIFTAcDistanceMatrix/cc
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../gift-config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LDFLAGS =  -lpthread
LIBS = -lpthread -lm 
libGIFTAcDistanceMatrix_la_LIBADD = 
am_libGIFTAcDistanceMatrix_la_OBJECTS =  plug_in_fo.lo
libGIFTAcDistanceMatrix_la_OBJECTS =  \
$(am_libGIFTAcDistanceMatrix_la_OBJECTS)
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXFLAGS = -g -O2 -I /usr/local/include/mysql -D__GIFT_WITH_PERL__ -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/lib/perl5/5.6.0/i686-linux/CORE -DHAVE_LIBPTHREAD
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES =  $(libGIFTAcDistanceMatrix_la_SOURCES)
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES =  # $(DEPDIR)/plug_in_fo.Plo
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

GZIP_ENV = --best
SOURCES = $(libGIFTAcDistanceMatrix_la_SOURCES)
OBJECTS = $(am_libGIFTAcDistanceMatrix_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .c .cc .lo .o .obj
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu libGIFTAcDistanceMatrix/cc/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  echo " $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p"; \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libGIFTAcDistanceMatrix.la: $(libGIFTAcDistanceMatrix_la_OBJECTS) $(libGIFTAcDistanceMatrix_la_DEPENDENCIES)
	$(CXXLINK) -rpath $(libdir) $(libGIFTAcDistanceMatrix_la_LDFLAGS) $(libGIFTAcDistanceMatrix_la_OBJECTS) $(libGIFTAcDistanceMatrix_la_LIBADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $$here

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

#include $(DEPDIR)/plug_in_fo.Plo

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf $(DEPDIR)

maintainer-clean-depend:

#CXXDEPMODE = depmode=none

.cc.o:
#	source='$<' object='$@' libtool=no 
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' 
#	$(CXXDEPMODE) $(depcomp) 
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cc.lo:
#	source='$<' object='$@' libtool=yes 
#	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' 
#	$(CXXDEPMODE) $(depcomp) 
	$(LTCXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cc.obj:
#	source='$<' object='$@' libtool=no 
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' 
#	$(CXXDEPMODE) $(depcomp) 
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_STRIP_FLAG=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-rm -f Makefile.in
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool clean-tags \
		clean-depend clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-depend \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: all all-am all-redirect check check-am clean clean-compile \
clean-depend clean-generic clean-libLTLIBRARIES clean-libtool \
clean-tags distclean distclean-compile distclean-depend \
distclean-generic distclean-libLTLIBRARIES distclean-libtool \
distclean-tags distdir dvi dvi-am info info-am install install-am \
install-data install-data-am install-exec install-exec-am \
install-libLTLIBRARIES install-strip installcheck installcheck-am \
installdirs maintainer-clean maintainer-clean-compile \
maintainer-clean-depend maintainer-clean-generic \
maintainer-clean-libLTLIBRARIES maintainer-clean-libtool \
maintainer-clean-tags mostlyclean mostlyclean-compile \
mostlyclean-depend mostlyclean-generic mostlyclean-libLTLIBRARIES \
mostlyclean-libtool mostlyclean-tags tags uninstall uninstall-am \
uninstall-libLTLIBRARIES


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
