# Makefile.in generated automatically by automake 1.4c from Makefile.am

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /home/wolfgang/gift-install
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

pkgdatadir = $(datadir)/gift
pkglibdir = $(libdir)/gift
pkgincludedir = $(includedir)/gift

top_builddir = ..

ACLOCAL = ${SHELL} /home/wolfgang/gift/missing --run aclocal
AUTOCONF = ${SHELL} /home/wolfgang/gift/missing --run autoconf
AUTOMAKE = ${SHELL} /home/wolfgang/gift/missing --run automake
AUTOHEADER = ${SHELL} /home/wolfgang/gift/missing --run autoheader

INSTALL = /usr/bin//ginstall -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :


host_alias = @host_alias@
host_triplet = i686-pc-linux-gnu
AMDEP = #
AMTAR = ${SHELL} /home/wolfgang/gift/missing --run tar
AS = @AS@
AWK = gawk
BAYESIAN = 
BAYESIAN_LD_ADD = 
CC = gcc
CONVERT = /usr/bin/X11/convert
CPP = /lib/cpp
CXX = g++
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DOXYGEN = /usr/bin//doxygen
ECHO = echo
EMACS = emacs
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GIFT_BAYESIAN_FLAG = 
GIFT_INTERNAL_FLAG = 
GIFT_INTERNAL_PERLS = 
GIFT_LIB_VERSION_INFO = -version-info 0:1:5
LEX = @LEX@
LIBADD_DL = @LIBADD_DL@
LIBOBJS = @LIBOBJS@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = ./ltmain.sh
LN_S = ln -s
MAINT = @MAINT@
MAKEINFO = ${SHELL} /home/wolfgang/gift/missing --run makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = gift
PERL = /usr/local/bin/perl
PERL_LD_ADD = -rdynamic  -L/usr/local/lib /usr/local/lib/perl5/5.6.0/i686-linux/auto/DynaLoader/DynaLoader.a -L/usr/local/lib/perl5/5.6.0/i686-linux/CORE -lperl -lnsl -lndbm -lgdbm -ldbm -ldb -ldl -lm -lc -lposix -lcrypt
PRE_INSTALL_LIBDIRS = -L/home/wolfgang/gift/libMRML/cc/ -L/home/wolfgang/gift/libGIFTAcPerl/cc/ -L/home/wolfgang/gift/libGIFTQuPerl/cc/ -L/home/wolfgang/gift/libGIFTAcInvertedFile/cc/ -L/home/wolfgang/gift/libGIFTAcHierarchy/cc/ -L/home/wolfgang/gift/libGIFTAcDistanceMatrix/cc/ -L/home/wolfgang/gift/libGIFTQuInvertedFile/cc/ -L/home/wolfgang/gift/libGIFTQuBayesian/cc/ -L/home/wolfgang/gift/libGIFTQuHierarchy/cc/ -L/home/wolfgang/gift/libGIFTAcURL2FTS/cc/
PRE_INSTALL_LINKDIRS = --rpath/home/wolfgang/gift/libMRML/cc/ -L/home/wolfgang/gift/libGIFTAcPerl/cc/ -L/home/wolfgang/gift/libGIFTQuPerl/cc/ --rpath/home/wolfgang/gift/libGIFTAcInvertedFile/cc/ --rpath/home/wolfgang/gift/libGIFTAcHierarchy/cc/ --rpath/home/wolfgang/gift/libGIFTAcDistanceMatrix/cc/ --rpath/home/wolfgang/gift/libGIFTQuInvertedFile/cc/ --rpath/home/wolfgang/gift/libGIFTQuBayesian/cc/ --rpath/home/wolfgang/gift/libGIFTQuHierarchy/cc/ --rpath/home/wolfgang/gift/libGIFTAcURL2FTS/cc/
PYTHON = @PYTHON@
PYTHON_EXEC_PREFIX = @PYTHON_EXEC_PREFIX@
PYTHON_PLATFORM = @PYTHON_PLATFORM@
PYTHON_PREFIX = @PYTHON_PREFIX@
PYTHON_SITE = @PYTHON_SITE@
PYTHON_SITE_EXEC = @PYTHON_SITE_EXEC@
PYTHON_SITE_INSTALL = @PYTHON_SITE_INSTALL@
PYTHON_SITE_PACKAGE = @PYTHON_SITE_PACKAGE@
PYTHON_VERSION = @PYTHON_VERSION@
RANLIB = ranlib
SGML2INFO = 
SGML2LATEX = 
SGML2TXT = 
STRIP = strip
U = @U@
UNPUBLISHED = 
VERSION = 0.1.5pre
WEB_PUBLISHING_DIRECTORY = /user/u7/muellerw/public_html/
WEB_PUBLISHING_LOCATION = http://localhost/~muellerw
install_sh = ./install-sh
lispdir = ${datadir}/emacs/site-lisp
multi_basedir = @multi_basedir@
pythondir = @pythondir@


noinst_DATA = system-doc configuring-and-hacking-the-gift.info configuring-and-hacking-the-gift.txt configuring-and-hacking-the-gift.dvi gift-guide.dvi gift-guide.txt gift-guide.info

CLEANFILES = gift-guide.info gift-guide.dvi configuring-and-hacking-the-gift.info configuring-and-hacking-the-gift.dvi autoDoc/HTML/* autoDoc/rtf/* autoDoc/man/*/* autoDoc/latex/*
subdir = Doc
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../gift-config.h
CONFIG_CLEAN_FILES = 
DIST_SOURCES = 
DATA =  $(noinst_DATA)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu Doc/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_STRIP_FLAG=-s install
installdirs:


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-rm -f Makefile.in
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: all all-am all-redirect check check-am clean clean-generic \
distclean distclean-generic distdir dvi dvi-am info info-am install \
install-am install-data install-data-am install-exec install-exec-am \
install-strip installcheck installcheck-am installdirs maintainer-clean \
maintainer-clean-generic mostlyclean mostlyclean-generic tags uninstall \
uninstall-am


gift-guide.info: gift-guide.sgml 
	- gift-guide.sgml

configuring-and-hacking-the-gift.info: configuring-and-hacking-the-gift.sgml
	- configuring-and-hacking-the-gift.sgml

gift-guide.txt: gift-guide.sgml 
	- gift-guide.sgml

configuring-and-hacking-the-gift.txt: configuring-and-hacking-the-gift.sgml
	- configuring-and-hacking-the-gift.sgml

gift-guide.dvi: gift-guide.sgml
	- gift-guide.sgml

configuring-and-hacking-the-gift.dvi: configuring-and-hacking-the-gift.sgml
	- configuring-and-hacking-the-gift.sgml

system-doc: Doxyfile 
	-mkdir autoDoc
	-mkdir autoDoc/HTML
	-/usr/bin//doxygen 

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
